defaults:
  - base_config
  - db: denodo
  - override hydra/job_logging: custom
  - _self_

hydra:
  # job:
  #   env_copy:
  #     - AD_USERNAME
  #     - AD_PASSWORD
  #     - TERADATA_PASSWORD
  run:
    dir: ./logs/hydra/outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./logs/hydra/multirun/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    params:
      dates.current_date: ${dates.range}